build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

filter:
    excluded_paths:
        - 'tests/*'
